
###############################################################################
#
# Inclusive Makefile for the l2table module.
#
# Autogenerated 2013-06-10 19:59:21.597446
#
###############################################################################
l2table_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(l2table_BASEDIR)/module/make.mk
include $(l2table_BASEDIR)/module/src/make.mk
include $(l2table_BASEDIR)/utest/_make.mk
