.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH IVS 8 "June 27, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ivs \- OpenFlow virtual switch
.SH SYNOPSIS
\fB ivs \fR
[\fB-hvt\fR]
[\fB-c\fIhost\fB[:\fIport\fR]]\&...
[\fB-i\fIinterface\fR]\&...
.SH DESCRIPTION
\fBivs\fP (Indigo Virtual Switch) is an OpenFlow virtual switch designed for
high performance and minimal administration. It uses the \fB\%openvswitch\fR
kernel module available in newer kernels or from the \fB\%openvswitch-datapath-dkms\fR
package.
.PP
.SH OPTIONS
.TP
\fB\-h\fR, \fB--help\fR
Show summary of options.
.TP
\fB\-v\fR, \fB--verbose\fR
Enable verbose logging.
.TP
\fB\-t\fR, \fB--trace\fR
Enable trace logging.
.TP
\fB\-i \fIinterface\fR, \fB--interface \fIinterface\fR
Add a network interface.
.TP
\fB\-c \fIhost\fB[:\fIport\fR], \fB--controller \fIhost\fB[:\fIport\fR]
Add a controller connection. \fIport\fR defaults to 6633.
.TP
\fB\-l \fIhost\fB[:\fIport\fR], \fB--listen \fIhost\fB[:\fIport\fR]
Add a listening socket (for dpctl). \fIport\fR defaults to 6634.
.TP
\fB--dpid \fIdpid\fR
Set the datapath ID. \fIdpid\fR should be 16 hex digits.
.TP
\fB--syslog\fR
Write log messages to syslog instead of stderr.
.TP
\fB--help\fR
Print usage information.
.TP
\fB--version\fR
Print version information.
.PP
.SH AUTHOR
ivs was written by the Indigo community <http://www.openflowhub.org/display/Indigo>.
.PP
This manual page was written by Rich Lane <rlane@bigswitch.com>.
